[package]
name = "grokemon-gateway"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
axum.workspace = true
grokemon-auth = { path = "../auth" }
grokemon-config = { path = "../config" }
grokemon-mgba = { path = "../mgba" }
http.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
uuid.workspace = true

[dev-dependencies]
tower.workspace = true
