[package]
name = "grokemon-instances"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
grokemon-config = { path = "../config" }
grokemon-ipc = { path = "../ipc" }
grokemon-mgba = { path = "../mgba" }
libc.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
